# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba4f1f1a3b5cc0f46e38e0ab4db411085b68c7883529b07a5944c17918db13835f4c1fd41fd69644f5f222ec106266a87418266f5d1890a85758644537a1f36

test:
  secret_key_base: 440237d08c1a3576ec7194fa6ab8d857929baa9325b127b35a5b93113fefced4ddc2242b7fda8df00b5b33c76c052dd9bf124f1fa2f1b43e84c86813234e73fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
